# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

permissions:
  id-token: write
  pages: write

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: ralismark/ralismark.github.io

      - name: Jekyll build
        run: |
          docker build . --tag=image
          docker run -e JEKYLL_ENV=production \
            -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            image jekyll build

      - name: Upload built site
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to gh-pages
        uses: actions/deploy-pages@v1.2.3

